Pimp pre-push hook

diff --git a/support/git/pre-push b/support/git/pre-push
--- a/support/git/pre-push
+++ b/support/git/pre-push
@@ -1,8 +1,45 @@
 #! /bin/bash
 
 function header {
-    echo "tothlaszlo.hu combo-breaker"
+    echo "tothlaszlo.hu push-breaker"
+}
+
+function git_checker {
+    echo -e 'Checking working directory...\c'
+    if [ -n "$(git status --porcelain)" ]; then
+      echo -e "\e[31mplease commit/stash your changes first!\e[0m\n"
+      mplayer support/git/sad-trompone.mp3 > /dev/null 2>&1
+      exit 1
+    else
+      echo -e "\e[32mclean!\e[0m\n"
+    fi
+}
+
+function test {
+    echo -e 'Running tests...\c'
+    npm test > /dev/null
+    check $?
+}
+
+function check {
+    if [ $1 == 0 ]; then
+        pass
+    else
+        failed
+    fi
+}
+
+function pass {
+    echo -e "\e[32mpassed!\e[0m\n"
+}
+
+function failed {
+    echo -e "\e[31mfailed!\e[0m\n"
+    mplayer support/git/sad-trompone.mp3  > /dev/null &
+    exit 1
 }
 
 header
+git_checker
+test
 exit 0
